# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mockd < Formula
  desc "High-performance multi-protocol API mocking server"
  homepage "https://mockd.io"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getmockd/mockd/releases/download/v0.6.0/mockd_0.6.0_darwin_amd64.tar.gz"
      sha256 "f7be337ce8f26401cb7081034f9cb096dbbe8c4f18a39b3d1753d0c13a2aed05"

      define_method(:install) do
        bin.install "mockd"
        bash_completion.install "completions/mockd.bash" => "mockd"
        zsh_completion.install "completions/mockd.zsh" => "_mockd"
        fish_completion.install "completions/mockd.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getmockd/mockd/releases/download/v0.6.0/mockd_0.6.0_darwin_arm64.tar.gz"
      sha256 "d5842d0ef5ae2158aa34c088412b0dd7f9749eaf076a1b69bfeee71a23abab18"

      define_method(:install) do
        bin.install "mockd"
        bash_completion.install "completions/mockd.bash" => "mockd"
        zsh_completion.install "completions/mockd.zsh" => "_mockd"
        fish_completion.install "completions/mockd.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getmockd/mockd/releases/download/v0.6.0/mockd_0.6.0_linux_amd64.tar.gz"
      sha256 "5aa7e68025683cba6e39cc9d10501b83787216fad3f628f67460d3c36b05305b"
      define_method(:install) do
        bin.install "mockd"
        bash_completion.install "completions/mockd.bash" => "mockd"
        zsh_completion.install "completions/mockd.zsh" => "_mockd"
        fish_completion.install "completions/mockd.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getmockd/mockd/releases/download/v0.6.0/mockd_0.6.0_linux_arm64.tar.gz"
      sha256 "1ebdec167cda57bf7b62d67b6852a0a75026b5d0e186f1a324673d2051796f4e"
      define_method(:install) do
        bin.install "mockd"
        bash_completion.install "completions/mockd.bash" => "mockd"
        zsh_completion.install "completions/mockd.zsh" => "_mockd"
        fish_completion.install "completions/mockd.fish"
      end
    end
  end

  test do
    system "#{bin}/mockd", "--version"
  end
end
