# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mockd < Formula
  desc "High-performance multi-protocol API mocking server"
  homepage "https://mockd.io"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/getmockd/mockd/releases/download/v0.6.0/mockd_0.6.0_darwin_amd64.tar.gz"
      sha256 "5774c01dc1afff32a52137e4ec3dfc2bab95dd99195549ea870cafcc11e4cc78"

      define_method(:install) do
        bin.install "mockd"
        bash_completion.install "completions/mockd.bash" => "mockd"
        zsh_completion.install "completions/mockd.zsh" => "_mockd"
        fish_completion.install "completions/mockd.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/getmockd/mockd/releases/download/v0.6.0/mockd_0.6.0_darwin_arm64.tar.gz"
      sha256 "020ac867a411b08ff0b37fc599eb16ae83abe144cb3ae339a1b45ddafa5ef6a4"

      define_method(:install) do
        bin.install "mockd"
        bash_completion.install "completions/mockd.bash" => "mockd"
        zsh_completion.install "completions/mockd.zsh" => "_mockd"
        fish_completion.install "completions/mockd.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/getmockd/mockd/releases/download/v0.6.0/mockd_0.6.0_linux_amd64.tar.gz"
      sha256 "5da184cda0a6bdab2bcffc0a7ff643514cb72d2172666d651f125b1195d5bb2e"
      define_method(:install) do
        bin.install "mockd"
        bash_completion.install "completions/mockd.bash" => "mockd"
        zsh_completion.install "completions/mockd.zsh" => "_mockd"
        fish_completion.install "completions/mockd.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/getmockd/mockd/releases/download/v0.6.0/mockd_0.6.0_linux_arm64.tar.gz"
      sha256 "1cd182a134b79359ef8fd1a8d94286637b8eda8a807f5c437994efb0115cca14"
      define_method(:install) do
        bin.install "mockd"
        bash_completion.install "completions/mockd.bash" => "mockd"
        zsh_completion.install "completions/mockd.zsh" => "_mockd"
        fish_completion.install "completions/mockd.fish"
      end
    end
  end

  test do
    system "#{bin}/mockd", "--version"
  end
end
